import type { Metadata } from "next";
import "@styles/reset.css";
import { Navbar } from "@components/navbar";
import styles from "./page.module.scss";
import { cx } from "@utils";
import { afacad, taiHeritagePro } from "@styles/font";

// TODO: update this
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          styles.bodyContainer,
          afacad.variable,
          taiHeritagePro.variable
        )}
      >
        <nav>
          <Navbar />
        </nav>
        <main className={styles.mainContainer}>{children}</main>
      </body>
    </html>
  );
}
