import type { Metadata } from "next";
import "./reset.css";
import { Navbar } from "@components/navbar";
import styles from "./page.module.scss";

// TODO: update this
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.bodyContainer} >
        <nav>
          <Navbar />
        </nav>
        <main className={styles.mainContainer} >{children}</main>
      </body>
    </html>
  );
}
